import { createRef } from "react";
import { vi } from "vitest";
import type { StudioPanelsState } from "./types";

const noop = vi.fn();
const t = (key: string) => key;

/** Minimal shared mock for studio panel smoke tests. */
export function createMockStudioPanelsState(
  overrides: Partial<StudioPanelsState> = {},
): StudioPanelsState {
  const base = {
    t,
    sortLocale: "en",
    p: { current: null },
    studioPane: "catalog" as const,
    setStudioPane: noop,
    library: null,
    libraryIndex: null,
    onReconcileLibrary: noop,
    onLibraryDelta: noop,
    onLibraryDeltas: noop,
    downloadSummaryLine: () => "",
    log: "",
    setLog: noop,
    metaLog: "",
    setMetaLog: noop,
    dlBusy: false,
    setDlBusy: noop,
    dlProg: null,
    setDlProg: noop,
    dlTrackProg: null,
    setDlTrackProg: noop,
    mkBusy: false,
    setMkBusy: noop,
    artBusy: false,
    setArtBusy: noop,
    metaBusy: false,
    setMetaBusy: noop,
    metaAllBusy: false,
    setMetaAllBusy: noop,
    metaScanProg: null,
    setMetaScanProg: noop,
    trackMetaBusy: false,
    setTrackMetaBusy: noop,
    trackAllBusy: false,
    setTrackAllBusy: noop,
    trackScanProg: null,
    setTrackScanProg: noop,
    titleSanBusy: false,
    setTitleSanBusy: noop,
    trackPruneBusy: false,
    setTrackPruneBusy: noop,
    trackPruneProg: null,
    setTrackPruneProg: noop,
    stopMetaAll: { current: false },
    stopTrackAll: { current: false },
    stopTrackPrune: { current: false },
    url: "",
    setUrl: noop,
    dlStudioMode: "classic" as const,
    setDlStudioMode: noop,
    catalogStudioMode: "local" as const,
    setCatalogStudioMode: noop,
    dlUrlMode: "single" as const,
    setDlUrlMode: noop,
    dlList: null,
    dlDirQuery: "",
    setDlDirQuery: noop,
    dlDirResults: [],
    dlDirSearchBusy: false,
    dlDirSearchOpen: false,
    setDlDirSearchOpen: noop,
    dlDirSearchInputRef: createRef<HTMLInputElement>(),
    dlPath: "",
    dlDestPicked: false,
    catalogLockedByEnv: false,
    serverLocalAccess: false,
    localSessionAccount: null,
    catalogData: null,
    mySelection: null,
    catalogBusy: false,
    catalogErr: null,
    catalogMsg: null,
    catalogArtistDetail: null,
    setCatalogArtistDetail: noop,
    catalogArtistQuery: "",
    setCatalogArtistQuery: noop,
    catalogArtistOnlyAttention: true,
    setCatalogArtistOnlyAttention: noop,
    artQuery: "",
    setArtQuery: noop,
    artRes: [],
    newDirName: "",
    setNewDirName: noop,
    metaArtistName: "",
    setMetaArtistName: noop,
    metaAlbumPath: "",
    setMetaAlbumPath: noop,
    metaArt: "",
    setMetaArt: noop,
    metaAlb: "",
    setMetaAlb: noop,
    coverPickArtist: "",
    setCoverPickArtist: noop,
    relPayload: null,
    relStreamComplete: false,
    relEnrichBusy: false,
    relSel: new Set<string>(),
    setRelSel: noop,
    relQuery: "",
    setRelQuery: noop,
    relLoadBusy: false,
    albumForCover: "",
    setAlbumForCover: noop,
    metaScanChoiceOpen: null,
    setMetaScanChoiceOpen: noop,
    discogsConfigured: false,
    discogsPickerOpen: false,
    setDiscogsPickerOpen: noop,
    discogsCandidates: [],
    metaOptionalOpen: false,
    setMetaOptionalOpen: noop,
    libraryArtistsSorted: [],
    studioMetaBusy: false,
    metaAlbumsForPick: [],
    coverAlbumsForPick: [],
    dlUrlPlaceholder: "",
    showMultiAlbumPicker: false,
    filteredRelEntries: [],
    filteredRelAlbums: [],
    filteredRelSongs: [],
    dlUrlValid: false,
    loadCatalogPane: noop,
    openCatalogArtist: noop,
    pickCatalogWebForDownload: noop,
    addArtistCatalog: noop,
    removeArtistCatalog: noop,
    addAlbumCatalog: noop,
    removeAlbumCatalog: noop,
    useCurrentForArt: noop,
    setMetaFromCurrent: noop,
    loadDlFs: noop,
    toggleDlDirSearch: noop,
    doCreateFolder: noop,
    fetchOneAlbumMeta: noop,
    applyDiscogsReleaseChoice: noop,
    runMetaScanAll: noop,
    fetchSelectedAlbumTracksMeta: noop,
    runTrackScanAll: noop,
    runPruneOrphanTrackMeta: noop,
    runSanitizeTitles: noop,
    stopStudioDownload: noop,
    hasValidDownloadDest: false,
    releasesDlBlockedAlbumFolder: false,
    exploreSingleBlockedArtistFolder: false,
    prepareExploreDownload: vi.fn(async () => false),
    runDl: noop,
    loadReleasesCatalog: noop,
    runReleasesDl: noop,
    toggleRelEntry: noop,
    dlMkdirBlockedInAlbum: false,
    dlProgNorm: null,
    dlTrackNorm: null,
    showDualDlProgressBar: false,
    singleDlBarNorm: null,
    showDlProgressWrap: false,
    doArtSearch: noop,
    applyCover: noop,
    filteredCatalogArtists: [],
    dlActiveDownloadIdRef: { current: null },
  };
  return { ...base, ...overrides } as StudioPanelsState;
}
